"""
Project Euler - Problem 12: Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from sympy import divisor_count

def solution():
    n = 1
    triangle = 1
    while True:
        if divisor_count(triangle) > 500:
            return triangle
        n += 1
        triangle += n

if __name__ == "__main__":
    print(solution())  # Answer: 76576500