"""
Project Euler - Problem 44: Pentagon Numbers

Pentagonal numbers are generated by the formula, P_n = n(3n-1)/2.
The first ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference,
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and
difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?
"""

def pentagonal(n):
    return n * (3 * n - 1) // 2

def is_pentagonal(x):
    for n in range(1, x):
        pn = pentagonal(n)
        if pn == x:
            return True
        if pn > x:
            return False

def solution():
    pentagonals = set()
    n = 1
    
    while True:
        pn = pentagonal(n)
        
        for pk in pentagonals:
            diff = pn - pk
            total = pn + pk
            
            if diff in pentagonals and is_pentagonal(total):
                return diff
        
        pentagonals.add(pn)
        n += 1

if __name__ == "__main__":
    print(solution())  # Answer: 5482660