"""
Project Euler - Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

import math
import scipy.constants
from sympy import fibonacci

def nth_fibonacci_less_than():
    return math.ceil(math.log(4000000 * math.sqrt(5)) / math.log(scipy.constants.golden))

def solution():
    return sum([fibonacci(i) for i in range(nth_fibonacci_less_than()) if fibonacci(i) % 2 == 0])

if __name__ == "__main__":
    print(solution())  # Answer: 4613732