"""
Project Euler - Problem 45: Triangular, Pentagonal, and Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T_n = n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal   P_n = n(3n-1)/2    1, 5, 12, 22, 35, ...
Hexagonal    H_n = n(2n-1)      1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

def is_pentagonal(x):
    n = (1 + (1 + 24 * x) ** 0.5) / 6
    return n == int(n) and n > 0

def is_triangular(x):
    n = (-1 + (1 + 8 * x) ** 0.5) / 2
    return n == int(n) and n > 0

def solution():
    n = 144  # Start from the next hexagonal number after H_143
    
    while True:
        hexagonal = n * (2 * n - 1)
        if is_pentagonal(hexagonal) and is_triangular(hexagonal):
            return hexagonal
        n += 1

if __name__ == "__main__":
    print(solution())  # Answer: 1533776805